# 예외 처리
## 1. 예외와 기본 예외처리
#### 예외 : 프로그램을 실행하는 동안 문제가 발생하면 프로그램이 자동으로 중단되는데 이렇게 발생한 오류<br>
#### 예외 처리 : 이러한 오류에 대처할 수 있게 하는 처리
* ##### 오류와 예외의 차이 : 예외는 오류에 포함되며 예외는 프로그램을 실행하면서 발생하는 논리적 오류이고 오류는 프로그램 실행 전에 발생하는 문법적 오류
#### 기본 예외 처리
```javascript
//undefined 자료형을 일반적인 객체 또는 함수처럼 다루면 TypeError 예외 발생
function callThree(callback){
  if(callback){ //조건식(undefined => false)
    for(let i=0;i<3;i++){
      callback();
    }
  }else{
    console.log('callback 미지정');
  }
}

callThree(fuction () {console.log('Hello'); }); //정상 실행

callThree();//undefined 예외 발생
```
<br>

## 2. 고급 예외 처리
- #### try catch finally 구문
```javascript
try{//예외 발생 시
  const array = new Array(-200);//RangeError 발생
}catch (exception){// 처리
  console.log('${exception.name} 예외 발생');
}finally{ //무조건 실행
  console.log('finally 구문 실행');
}
```
<br>

## 3. 예외 객체
#### try catch 구문의 괄호 안에 들어있는 변수
```javascript

try{
  error.error.error();
}catch(exception){
  console.log(exception.name); //예외 객체의 name 속성
  console.log(exception.message); //예외 객체의 message 속성
}

```

<br>

## 4. 예외 강제 발생
- #### throw와 Error 객체 사용
```javascript

try{
  const error = new Error('메시지');
  error.name = '오류의 이름 속성';
  error.message = '오류의 메시지 속성';
  
  throw error; // 에러 발생
}catch (exception){
  console.log('${exception.name} 예외가 발생');
  console.log(exception.message);
}

```
